import { useEffect, useRef, useState } from 'react';
import { countries, cityById, countryById } from '../content/countries';
import { act, careers, createGame, formatMoney, furniture, goals, options } from '../game/simulation/engine';
import { drawEvent } from '../game/events/catalog';
import type { Choice } from '../game/simulation/engine';
import type { Mode } from '../game/simulation/types';
import { useGame } from './store';
import { exportGame, importGame, saveGame } from '../storage/save';
import { World } from '../ui/World';
import { App as NativeApp } from '@capacitor/app';
import { Haptics, ImpactStyle } from '@capacitor/haptics';
type Tab = 'Inicio' | 'Mapa' | 'Trabajo' | 'Social' | 'Objetivos';
const tabs: { name: Tab; icon: string }[] = [{ name: 'Inicio', icon: '⌂' }, { name: 'Mapa', icon: '◇' }, { name: 'Trabajo', icon: '▣' }, { name: 'Social', icon: '♡' }, { name: 'Objetivos', icon: '◎' }];
const tap = () => void Haptics.impact({ style: ImpactStyle.Light }).catch(() => {});

export default function App() {
  const { game, start, decide, replace, setGoal, setCareer } = useGame();
  const [tab, setTab] = useState<Tab>('Inicio'); const [place, setPlace] = useState<string | null>(null); const [settings, setSettings] = useState(false); const [message, setMessage] = useState(''); const [work, setWork] = useState<Choice | null>(null);
  const file = useRef<HTMLInputElement>(null);
  useEffect(() => { const listener = NativeApp.addListener('backButton', () => { if (place) setPlace(null); else if (settings) setSettings(false); else setTab('Inicio'); }); return () => { void listener.then(l => l.remove()); }; }, [place, settings]);
  useEffect(() => { const onVisibility = () => { if (document.visibilityState === 'hidden' && game) saveGame(game); }; document.addEventListener('visibilitychange', onVisibility); return () => document.removeEventListener('visibilitychange', onVisibility); }, [game]);
  if (!game) return <Setup onStart={start} onImport={() => file.current?.click()} file={file} onFile={async f => { try { replace(await importGame(f)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Archivo inválido'); } }} message={message} />;
  const country = countryById(game.countryId), city = cityById(country, game.cityId), event = drawEvent(game);
  const action = (choice: Choice) => { tap(); if (choice.action === 'work' && choice.performance === undefined) { setPlace(null); setWork(choice); } else decide(choice); };
  const placeAction = (name: string) => { tap(); setPlace(name); };
  const buy = (item: string) => action({ id: `buy-${item}`, label: item, action: 'shop', item, cost: Math.round(country.salaries * (item === 'Computadora' ? .8 : .36)), hours: 1 });
  return <main className="app-shell">
    <header className="topbar"><div className="brand">VIDA<span className="brand-dot">.</span><small> TU VIDA EN MOVIMIENTO</small></div><button className="icon-button" onClick={() => setSettings(true)} aria-label="Opciones">☷</button></header>
    <div className="scroll-area" key={tab}>
      <div className="eyebrow">DÍA {game.day} <span className="sep">/</span> {String(game.hour).padStart(2, '0')}:00 <span className="sep">/</span> {city.name.toUpperCase()}</div>
      {tab === 'Inicio' && <>
        <section className="hero"><div><span className="eyebrow light">UNA VIDA POR CONSTRUIR</span><h1>Hola, {game.name}.</h1><p>{game.journal[0]?.text}</p></div><div className="avatar"><div className="avatar-hair"/><div className="avatar-face"/><div className="avatar-body"/></div></section>
        <div className="balance"><div><span>DISPONIBLE</span><strong>{formatMoney(game, game.money)}</strong></div><div className="balance-arrow">↗</div></div>
        <div className="vitals"><Vital label="Energía" value={game.energy} color="teal"/><Vital label="Ánimo" value={game.mood} color="orange"/><Vital label="Comida" value={game.food} color="blue"/></div>
        <div className="section-heading"><h2>¿Qué hacemos hoy?</h2><span>EL TIEMPO ES TUYO</span></div><div className="actions">{options(game).map((choice, i) => <button key={choice.id} className="action-card" onClick={() => action(choice)}><span className="action-icon">{['▣','✦','♡','◒','☾'][i]}</span><span>{choice.label}<small>{choice.hours} h{choice.cost ? ` · ${formatMoney(game, choice.cost)}` : ''}</small></span><b>→</b></button>)}</div>
        {event && !game.recentEvents.includes(event.id) && <section className="event-card"><div className="eyebrow">LA CIUDAD HABLA · {event.category.toUpperCase()}</div><p>{event.text(game)}</p><div className="inline-actions">{event.choices.map((choice, i) => <button key={choice.label} onClick={() => { const next = act(game, { id: event.id, label: choice.label, action: i === 0 ? 'social' : 'rest', hours: 1, npcId: game.npcs[(game.day + Number(event.id.split('-').at(-1))) % game.npcs.length].id }); replace({ ...next, recentEvents: [event.id, ...game.recentEvents].slice(0, 25) }); }}>{choice.label}</button>)}</div></section>}
        <div className="section-heading"><h2>Tu historia</h2><span>ÚLTIMOS MOMENTOS</span></div><div className="timeline">{game.journal.slice(0, 5).map((entry, i) => <div key={`${entry.day}-${i}`}><span>DÍA {entry.day}</span><p>{entry.text}</p></div>)}</div>
      </>}
      {tab === 'Mapa' && <><div className="page-heading"><h1>La ciudad</h1><p>Un lugar cambia según la hora y las personas que lo habitan.</p></div><World game={game} onPlace={placeAction}/><div className="section-heading"><h2>Barrios</h2><span>TOCÁ PARA VIAJAR</span></div><div className="districts">{city.districts.map((district, i) => <button key={district} className={game.district === i ? 'selected' : ''} onClick={() => action({ id: 'travel', label: district, action: 'travel', district: i, cost: i === game.district ? 0 : country.transport, hours: i === game.district ? 0 : 1, energy: i === game.district ? 0 : 4 })}>{district}<small>{i === game.district ? 'ESTÁS ACÁ' : `${formatMoney(game, country.transport)} · 1 H`}</small></button>)}</div><div className="place-grid">{city.landmarks.map(name => <button key={name} onClick={() => placeAction(name)}>{name}<b>↗</b></button>)}</div></>}
      {tab === 'Trabajo' && <><div className="page-heading"><h1>Tu camino</h1><p>Las oportunidades se construyen con práctica, formación y decisiones.</p></div><div className="feature-card"><span className="eyebrow">PROFESIÓN ACTUAL</span><h2>{game.career}</h2><p>{game.employed ? 'Tenés empleo. Tu experiencia abre nuevas puertas.' : 'Estás buscando un puesto. Mejorar tus habilidades ayuda.'}</p><div className="stat-row"><span>Experiencia <b>{game.experience} turnos</b></span><span>Formación <b>{game.skill}/100</b></span></div></div><div className="section-heading"><h2>Dar el próximo paso</h2></div><div className="actions">{options(game).slice(0, 2).map(choice => <button className="action-card" key={choice.id} onClick={() => action(choice)}><span className="action-icon">✦</span><span>{choice.label}<small>{choice.hours} horas</small></span><b>→</b></button>)}<button className="action-card" onClick={() => action({ id: 'freelance', label: 'Encargo', action: 'freelance', hours: 3, energy: 16 })}><span className="action-icon">↗</span><span>Hacer un encargo<small>3 horas · ingreso extra</small></span><b>→</b></button></div><div className="section-heading"><h2>Explorar profesiones</h2></div><div className="chips">{careers.map(career => <button key={career} className={game.career === career ? 'active' : ''} onClick={() => setCareer(career)}>{career}</button>)}</div></>}
      {tab === 'Social' && <><div className="page-heading"><h1>Las personas</h1><p>Las relaciones crecen con tiempo compartido. Algunas cosas se recuerdan.</p></div><div className="npc-list">{game.npcs.map(npc => <article className="npc-card" key={npc.id}><div className="npc-avatar">{npc.name[0]}</div><div className="npc-content"><div className="npc-title"><strong>{npc.name}</strong><span>{npc.profession}</span></div><p>{npc.traits.join(' · ')} · Suele estar en {npc.location.toLowerCase()}.</p><div className="relationship">Cercanía <span>{npc.friendship}/100</span><i style={{ width: `${npc.friendship}%` }}/></div>{npc.memories.length > 0 && <small>Recuerda: {npc.memories.at(-1)}</small>}<button onClick={() => action({ id: `meet-${npc.id}`, label: `Ver a ${npc.name}`, action: 'social', npcId: npc.id, hours: 2, energy: 8 })}>Pasar tiempo juntos →</button></div></article>)}</div></>}
      {tab === 'Objetivos' && <><div className="page-heading"><h1>A tu manera</h1><p>No existe una única vida correcta. Elegí algo que hoy te importe.</p></div><div className="feature-card goal-card"><span className="eyebrow">TU OBJETIVO</span><h2>{game.goal}</h2><p>Día {game.day} · {game.mode === '30-dias' ? 'Desafío de 30 días' : 'A tu propio ritmo'}</p></div><div className="goal-list">{goals.map(goal => <button key={goal} className={game.goal === goal ? 'chosen' : ''} onClick={() => setGoal(goal)}><span>{goal}</span><b>{game.goal === goal ? '✓' : '○'}</b></button>)}</div><div className="section-heading"><h2>Tu patrimonio</h2></div><div className="finance-grid"><div><span>EFECTIVO</span><strong>{formatMoney(game, game.money)}</strong></div><div><span>DEUDA</span><strong>{formatMoney(game, game.debt)}</strong></div><div><span>HOGAR</span><strong>{['Habitación', 'Monoambiente', 'Departamento'][game.home]}</strong></div></div>{game.debt > 0 && <button className="primary-button" onClick={() => action({ id: 'repay', label: 'Pagar deuda', action: 'repay', cost: Math.min(game.debt, game.money), hours: 1 })}>Pagar deuda</button>}<div className="section-heading"><h2>Tu casa</h2></div><p className="muted">{game.furniture.join(' · ')}</p><div className="chips">{furniture.filter(item => !game.furniture.includes(item)).map(item => <button key={item} onClick={() => buy(item)}>{item} · {formatMoney(game, Math.round(country.salaries * (item === 'Computadora' ? .8 : .36)))}</button>)}</div>{game.home < 2 && <button className="secondary-button" onClick={() => action({ id: 'move', label: 'Mudarse', action: 'move', cost: country.rent * 2, hours: 4, energy: 12 })}>Mudarse · {formatMoney(game, country.rent * 2)}</button>}</>}
    </div>
    <nav className="bottom-nav" aria-label="Navegación principal">{tabs.map(item => <button key={item.name} className={tab === item.name ? 'active' : ''} onClick={() => { tap(); setTab(item.name); setPlace(null); }}><span>{item.icon}</span><small>{item.name}</small></button>)}</nav>
    {place && <div className="scrim" onClick={() => setPlace(null)}><div className="sheet" onClick={e => e.stopPropagation()}><div className="sheet-handle"/><span className="eyebrow">{city.name.toUpperCase()} · {city.districts[game.district].toUpperCase()}</span><h2>{place}</h2><p>Un rincón de la ciudad para escribir la próxima parte de tu historia.</p><div className="actions">{options(game).filter(o => place === 'Casa' ? ['rest','eat','study'].includes(o.action) : place.includes('Trabajo') ? ['work','job'].includes(o.action) : place.includes('Instituto') ? o.action === 'study' : place.includes('Supermercado') || place.includes('Tienda') ? o.action === 'eat' : o.action === 'social').map(choice => <button className="action-card" key={choice.id} onClick={() => { action(choice); setPlace(null); }}><span className="action-icon">✦</span><span>{choice.label}</span><b>→</b></button>)}</div><button className="text-button" onClick={() => setPlace(null)}>Cerrar</button></div></div>}
    {work && <WorkChallenge key={`${game.day}-${game.hour}`} career={game.career} onFinish={score => { decide({ ...work, performance: score }); setWork(null); }} onCancel={() => setWork(null)}/>}
    {settings && <div className="scrim" onClick={() => setSettings(false)}><div className="sheet" onClick={e => e.stopPropagation()}><div className="sheet-handle"/><span className="eyebrow">TU PARTIDA</span><h2>Opciones</h2><p>La partida se guarda automáticamente en este dispositivo.</p><button className="secondary-button" onClick={() => { saveGame(game); setMessage('Partida guardada.'); }}>Guardar ahora</button><button className="secondary-button" onClick={() => exportGame(game)}>Exportar partida</button><button className="secondary-button" onClick={() => file.current?.click()}>Importar partida</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={async e => { const f = e.target.files?.[0]; if (f) try { replace(await importGame(f)); setSettings(false); } catch (error) { setMessage(error instanceof Error ? error.message : 'Archivo inválido'); } e.target.value = ''; }}/>{message && <p role="status">{message}</p>}<button className="text-button" onClick={() => setSettings(false)}>Cerrar</button></div></div>}
  </main>;
}

function Vital({ label, value, color }: { label: string; value: number; color: string }) { return <div className="vital"><span>{label}</span><strong>{value}%</strong><div><i className={color} style={{ width: `${value}%` }}/></div></div>; }
function WorkChallenge({ career, onFinish, onCancel }: { career: string; onFinish: (score: number) => void; onCancel: () => void }) {
  const [position, setPosition] = useState(0); const [round, setRound] = useState(0); const [scores, setScores] = useState<number[]>([]);
  useEffect(() => { let frame = 0; let last = 0; const loop = (time: number) => { if (time - last > 25) { setPosition((Math.sin(time / 470) + 1) / 2); last = time; } frame = requestAnimationFrame(loop); }; frame = requestAnimationFrame(loop); return () => cancelAnimationFrame(frame); }, []);
  const hit = () => { tap(); const score = Math.max(0, 1 - Math.abs(position - [0.42, 0.63, 0.5][round]) * 2.4); if (round === 2) onFinish((scores.reduce((sum, n) => sum + n, 0) + score) / 3); else { setScores([...scores, score]); setRound(round + 1); } };
  return <div className="scrim"><div className="sheet work-sheet"><div className="sheet-handle"/><span className="eyebrow">TURNO EN {career.toUpperCase()} · {round + 1}/3</span><h2>Encontrá el momento.</h2><p>Detené el marcador dentro de la zona verde. Tres tareas breves definen cómo sale tu turno.</p><div className="timing-track"><div className="timing-target" style={{ left: `${[42, 63, 50][round]}%` }}/><div className="timing-marker" style={{ left: `${position * 100}%` }}/></div><button className="primary-button" onClick={hit}>Resolver tarea</button><button className="text-button" onClick={onCancel}>Volver</button></div></div>;
}
function Setup({ onStart, onImport, file, onFile, message }: { onStart: (game: ReturnType<typeof createGame>) => void; onImport: () => void; file: React.RefObject<HTMLInputElement | null>; onFile: (file: File) => void; message: string }) {
  const [name, setName] = useState(''); const [countryId, setCountryId] = useState('ar'); const [cityId, setCityId] = useState('san-juan'); const [mode, setMode] = useState<Mode>('vida');
  const country = countryById(countryId);
  return <main className="setup"><div className="setup-art"><div className="setup-sun"/><div className="setup-mountain a"/><div className="setup-mountain b"/><div className="setup-building one"/><div className="setup-building two"/><div className="setup-building three"/><span>VIDA<span>.</span></span><small>TU VIDA. TU CIUDAD. TUS DECISIONES.</small></div><div className="setup-form"><span className="eyebrow">COMENZÁ TU HISTORIA</span><h1>Todo empieza<br/>con una decisión.</h1><label>¿Cómo te llamás?<input value={name} maxLength={24} placeholder="Tu nombre" onChange={e => setName(e.target.value)} /></label><div className="setup-row"><label>País<select value={countryId} onChange={e => { const c = countryById(e.target.value); setCountryId(c.id); setCityId(c.cities[0].id); }}>{countries.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Ciudad<select value={cityId} onChange={e => setCityId(e.target.value)}>{country.cities.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="mode-selector"><span>MODO DE JUEGO</span><button className={mode === 'vida' ? 'selected' : ''} onClick={() => setMode('vida')}>VIDA <small>Sin límites. Tu historia.</small></button><button className={mode === '30-dias' ? 'selected' : ''} onClick={() => setMode('30-dias')}>30 DÍAS <small>Un objetivo, poco tiempo.</small></button><button className={mode === 'diario' ? 'selected' : ''} onClick={() => setMode('diario')}>DESAFÍO DIARIO <small>La misma semilla para todos hoy.</small></button></div><button className="primary-button" onClick={() => onStart(createGame(name, countryId, cityId, mode, mode === 'diario' ? Number(new Date().toISOString().slice(0, 10).replaceAll('-', '')) : Date.now()))}>Empezar mi vida <span>→</span></button><button className="text-button" onClick={onImport}>Importar partida</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={e => { const f = e.target.files?.[0]; if (f) onFile(f); }}/>{message && <p role="alert">{message}</p>}<p className="disclaimer">Economías ficticias para el juego · Disponible sin conexión</p></div></main>;
}
